#!/usr/bin/env bash
# Derive a per-user "flavor" profile for recipes from the local git history,
# and print it as a profile.sh fragment. Read-only — prints to stdout, never
# writes. Redirect to install:
#
#   bash scripts/derive-flavor.sh > ~/.claude/skills/delegate-local/profile.sh
#
# This is the "analyse my own corpus" step of the portable-recipes design
# (ADR 0013): instead of every recipe carrying the maintainer's baked-in style
# numbers, delegate.sh sources the profile (same owner/mode trust check as
# config.sh) and exposes each FLAVOR_* variable as a {{flavor_*}} recipe
# placeholder, so the commit-message template carries the user's OWN
# subject-length norm and conventional-commit type vocabulary. Re-run after the
# history grows to refresh, or hand-edit the printed values to taste — the
# onboarding wizard will eventually wrap this with confirm-or-edit prompts.
#
# Usage: derive-flavor.sh [--ref <git-ref>] [--count N]
#   --ref    git ref to read history from (default: main, falls back to HEAD)
#   --count  how many recent non-merge commits to sample (default: 200)
set -euo pipefail

ref="main"
count=200
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ref) ref="${2:?--ref requires a value}"; shift 2;;
    --count) count="${2:?--count requires a value}"; shift 2;;
    -h|--help) grep '^#' "$0" | sed 's/^#\{1,2\} \{0,1\}//'; exit 0;;
    *) echo "derive-flavor: unknown arg '$1'" >&2; exit 2;;
  esac
done

command -v git >/dev/null 2>&1 || { echo "git not on PATH" >&2; exit 1; }
git rev-parse --git-dir >/dev/null 2>&1 || { echo "not in a git repository" >&2; exit 1; }
# Fall back to HEAD when the named ref doesn't exist (fresh clone, detached, or
# a default-branch name other than main).
git rev-parse --verify -q "$ref" >/dev/null 2>&1 || ref="HEAD"

# Subjects with the GitHub squash "(#NN)" suffix stripped — that suffix is
# appended by the merge, not authored, so it must not skew the length norm or
# leak into the type parse. (The commit-message recipe strips it too.)
subjects=$(git log "$ref" --no-merges --pretty=format:'%s' -"$count" | sed -E 's/ \(#[0-9]+\)$//')
[[ -n "$subjects" ]] || { echo "no commits found on $ref" >&2; exit 1; }
n=$(printf '%s\n' "$subjects" | grep -c .)

# Subject-length norm: the 90th-percentile authored length. A cap derived from
# what the user actually tolerates beats an abstract 50/72 convention; the
# onboarding step can still offer to tighten it.
subject_max=$(printf '%s\n' "$subjects" | awk '{print length}' | sort -n \
  | awk '{a[NR]=$1} END{ i=int(NR*0.9); if (i<1) i=1; print a[i] }')

# Conventional-commit type vocabulary, ordered by frequency (most-used first),
# comma-joined to match the recipe's "(feat, fix, docs, …)" allowed-type list.
# Only well-formed `type:` / `type(scope):` prefixes count, and a type must
# appear at least twice to make the list — that drops one-off typos (e.g. an
# `experiments:` next to the real `experiment:`) without losing genuine usage.
types=$(printf '%s\n' "$subjects" | sed -nE 's/^([a-z]+)(\([^)]*\))?:.*/\1/p' \
  | sort | uniq -c | sort -rn | awk '$1>=2{printf "%s, ", $2}' | sed 's/, *$//')

printf '# delegate-local flavor profile — generated by scripts/derive-flavor.sh\n'
printf '# Source corpus: %s non-merge commits on %s. Re-run to refresh, or edit to taste.\n' "$n" "$ref"
# Only emit a value when it's non-empty: a corpus with no conventional-commit
# prefixes leaves $types empty, and writing FLAVOR_COMMIT_TYPES="" would override
# the shipped default with an empty list. Omitting the line lets load-flavor fall
# back to flavor-defaults.sh instead.
[[ -n "$subject_max" ]] && printf 'FLAVOR_COMMIT_SUBJECT_MAX=%s\n' "$subject_max"
[[ -n "$types" ]] && printf 'FLAVOR_COMMIT_TYPES="%s"\n' "$types"
