#!/usr/bin/env bash
# Print a per-user override config for delegate-to-ollama based on what's
# actually installed in Ollama right now. Read-only — prints to stdout and
# never writes. Redirect to your override path if you like the result:
#
#   bash scripts/init.sh > ~/.claude/skills/delegate-to-ollama/config.sh
#
# After that, pick-model.sh sources the override after the shipped defaults
# and uses the adjusted preference order. The shipped defaults remain the
# fallback when no override is installed, and any tier the override doesn't
# touch falls through to its shipped list unchanged.
#
# Re-run after pulling new models to refresh the override.

set -euo pipefail

if ! command -v ollama >/dev/null 2>&1; then
  echo "ollama not on PATH" >&2
  exit 1
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pick="$script_dir/pick-model.sh"

installed=$(ollama list 2>/dev/null | awk 'NR>1 {print $1}')
if [[ -z "$installed" ]]; then
  echo "no models installed; nothing to personalise" >&2
  exit 1
fi

# Tier list parsed from pick-model.sh's TIERS= line — single source of truth.
tiers_line=$(grep -E '^TIERS="' "$pick" | head -1)
tiers=$(echo "$tiers_line" | sed -E 's/^TIERS="([^"]+)".*/\1/' | tr '|' ' ')

# Extract the shipped prefs list for a given tier by parsing the case
# statement in pick-model.sh. Avoids duplicating the prefs lists here so
# the init output stays in sync if the shipped order changes.
shipped_prefs() {
  local tier="$1"
  perl -ne '
    if (/^\s*\Q'"$tier"'\E\)\s*prefs=\(([^)]*)\)/) {
      my $list = $1;
      while ($list =~ /"([^"]+)"/g) { print "$1\n"; }
      exit;
    }
  ' "$pick"
}

cat <<'EOF'
# Per-user override for delegate-to-ollama, generated by scripts/init.sh.
# Sourced by pick-model.sh after the shipped defaults are set; reassigns
# `prefs` for each tier to put currently-installed models first while
# keeping the shipped list as a fallback.
#
# Hand-edit any tier to change ordering. Re-run init.sh after pulling
# new models to refresh.

case "$tier" in
EOF

# Escape double-quote, backslash, dollar, and backtick in a string before
# emitting it inside double-quotes in the generated bash. Ollama's name
# grammar restricts these characters in practice; this is defense in depth
# against the F3 finding in
# experiments/sessions/2026-05-03-security-review-delegation/RETROSPECTIVE.md.
escape_dq() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//\$/\\\$}"
  s="${s//\`/\\\`}"
  printf '%s' "$s"
}

for tier in $tiers; do
  shipped=$(shipped_prefs "$tier")
  [[ -z "$shipped" ]] && continue
  installed_first=()
  remaining=()
  while IFS= read -r p; do
    [[ -z "$p" ]] && continue
    if printf '%s\n' "$installed" | grep -qF -- "$p"; then
      installed_first+=("$p")
    else
      remaining+=("$p")
    fi
  done <<< "$shipped"
  parts=""
  if [[ ${#installed_first[@]} -gt 0 ]]; then
    for p in "${installed_first[@]}"; do parts+="\"$(escape_dq "$p")\" "; done
  fi
  if [[ ${#remaining[@]} -gt 0 ]]; then
    for p in "${remaining[@]}"; do parts+="\"$(escape_dq "$p")\" "; done
  fi
  parts="${parts% }"
  printf "  %s) prefs=(%s) ;;\n" "$tier" "$parts"
done

echo "esac"
