#!/usr/bin/env bash
# Print a per-user override config for delegate-local from what the running
# providers serve right now. Read-only; redirect to install:
#
#   mkdir -p ~/.local/share/delegate-local
#   bash scripts/init.sh > ~/.local/share/delegate-local/config.sh
#
# pick-model.sh sources it after the shipped defaults; untouched tiers fall
# through unchanged. Re-run after pulling new models.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pick="$script_dir/pick-model.sh"

# Asks pick-model.sh, which consumes the override, so the two agree on "installed".
installed=$(bash "$pick" --print-installed 2>/dev/null)
if [[ -z "$installed" ]]; then
  echo "no models installed; nothing to personalise" >&2
  exit 1
fi

# Tier list parsed from pick-model.sh's TIERS= line — single source of truth.
tiers_line=$(grep -E '^TIERS="' "$pick" | head -1)
tiers=$(echo "$tiers_line" | sed -E 's/^TIERS="([^"]+)".*/\1/' | tr '|' ' ')

# Via --print-prefs, never by re-parsing the case statement.
shipped_prefs() {
  local tier="$1"
  bash "$pick" --print-prefs 2>/dev/null | grep "^$tier:" | head -1 | sed 's/^[^:]*://' | tr ' ' '\n'
}

cat <<'EOF'
# Per-user override for delegate-local, generated by scripts/init.sh.
# Sourced by pick-model.sh after the shipped defaults are set; reassigns
# `prefs` for each tier to put currently-installed models first while
# keeping the shipped list as a fallback.
#
# Hand-edit any tier to change ordering. Re-run init.sh after pulling
# new models to refresh.

case "$tier" in
EOF

# Model names are emitted inside double quotes in generated bash, so the
# characters bash would interpret there are escaped: defence in depth.
escape_dq() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//\$/\\\$}"
  s="${s//\`/\\\`}"
  printf '%s' "$s"
}

for tier in $tiers; do
  shipped=$(shipped_prefs "$tier")
  [[ -z "$shipped" ]] && continue
  installed_first=()
  remaining=()
  while IFS= read -r p; do
    [[ -z "$p" ]] && continue
    if printf '%s\n' "$installed" | grep -qF -- "$p"; then
      installed_first+=("$p")
    else
      remaining+=("$p")
    fi
  done <<< "$shipped"
  parts=""
  if [[ ${#installed_first[@]} -gt 0 ]]; then
    for p in "${installed_first[@]}"; do parts+="\"$(escape_dq "$p")\" "; done
  fi
  if [[ ${#remaining[@]} -gt 0 ]]; then
    for p in "${remaining[@]}"; do parts+="\"$(escape_dq "$p")\" "; done
  fi
  parts="${parts% }"
  printf "  %s) prefs=(%s) ;;\n" "$tier" "$parts"
done

echo "esac"
